"use client";

import { useEffect, useState } from "react";
import { Check, CircleCheck, Clock3, Copy, Download, Eye, KeyRound, Layers3, Link2, LoaderCircle, MessageSquare, Newspaper, Pin, RefreshCw, Send, ShieldCheck, ShieldOff, Trash2 } from "lucide-react";

function formatDate(value) {
  if (!value) return "—";
  return new Intl.DateTimeFormat("ru-RU", { day: "numeric", month: "short", year: "numeric", hour: "2-digit", minute: "2-digit" }).format(new Date(value));
}

function updateCategory(value) {
  return value === "milestone" ? "Веха" : value === "document" ? "Документы" : value === "deadline" ? "Сроки" : value === "important" ? "Важно" : "Прогресс";
}

export default function PublicShareManager({ projectId, projects = [] }) {
  const [shares, setShares] = useState([]);
  const [status, setStatus] = useState("loading");
  const [error, setError] = useState("");
  const [days, setDays] = useState(14);
  const [pin, setPin] = useState("");
  const [credentials, setCredentials] = useState(null);
  const [copied, setCopied] = useState("");
  const [confirmRevoke, setConfirmRevoke] = useState("");
  const [publicOrigin, setPublicOrigin] = useState("");
  const [publishedDocuments, setPublishedDocuments] = useState([]);
  const [syncStatus, setSyncStatus] = useState("idle");
  const [syncMessage, setSyncMessage] = useState("");
  const [decisions, setDecisions] = useState([]);
  const [feedback, setFeedback] = useState([]);
  const [feedbackDrafts, setFeedbackDrafts] = useState({});
  const [feedbackBusy, setFeedbackBusy] = useState("");
  const [updates, setUpdates] = useState([]);
  const [updateDraft, setUpdateDraft] = useState({ title: "", content: "", category: "progress", pinned: false });
  const [updateBusy, setUpdateBusy] = useState("");
  const [confirmUpdateDelete, setConfirmUpdateDelete] = useState("");
  const [selectedProjectIds, setSelectedProjectIds] = useState(projectId ? [projectId] : []);

  useEffect(() => { setSelectedProjectIds(projectId ? [projectId] : []); loadShares(); }, [projectId]);

  function shareUrl(token) {
    return publicOrigin ? `${publicOrigin}/share/${token}` : `/share/${token}`;
  }

  function snapshotProjects(snapshot) {
    return Array.isArray(snapshot?.projects) ? snapshot.projects : snapshot?.project ? [snapshot] : [];
  }

  function documentsFor(snapshot, projectIds) {
    const selected = new Set(projectIds);
    return snapshotProjects(snapshot).filter(item => selected.has(item.project?.id)).flatMap(item => item.documents || []);
  }

  async function relay(envelope) {
    if (!envelope?.bridge) throw new Error("Не удалось подготовить защищённый запрос");
    const { endpoint, body, timestamp, nonce, signature } = envelope.bridge;
    const response = await fetch(endpoint, {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
        "X-Kontur-Timestamp": timestamp,
        "X-Kontur-Nonce": nonce,
        "X-Kontur-Signature": signature,
      },
      body,
    });
    const data = await response.json();
    if (!response.ok) throw new Error(data.error || "Публичный портал недоступен");
    let requestPayload = {};
    try { requestPayload = JSON.parse(body); } catch { /* signed body is generated by our server */ }
    return { ...data, origin: envelope.origin, snapshot: requestPayload.snapshot || null };
  }

  async function loadShares() {
    if (!projectId) return;
    setStatus("loading");
    setError("");
    try {
      const response = await fetch(`/api/public-share?admin=1&projectId=${encodeURIComponent(projectId)}`, { cache: "no-store" });
      const envelope = await response.json();
      if (!response.ok) throw new Error(envelope.error || "Не удалось загрузить ссылки");
      const data = await relay(envelope);
      setShares(data.shares || []);
      setPublicOrigin(data.origin || "");
      setPublishedDocuments(documentsFor(data.snapshot, [projectId]));
      setDecisions(data.decisions || []);
      setFeedback(data.feedback || []);
      setUpdates(data.updates || []);
      await importDecisions(data.decisions || []);
      await importFeedback(data.feedback || []);
      setStatus("ready");
    } catch (loadError) {
      setError(loadError.message || "Не удалось загрузить ссылки");
      setStatus("error");
    }
  }

  async function action(payload) {
    setError("");
    try {
      const response = await fetch("/api/public-share", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ projectId, ...payload }) });
      const envelope = await response.json();
      if (!response.ok) throw new Error(envelope.error || "Не удалось выполнить действие");
      const data = await relay(envelope);
      setShares(data.shares || []);
      setDecisions(data.decisions || []);
      setFeedback(data.feedback || []);
      setUpdates(data.updates || []);
      await importDecisions(data.decisions || []);
      await importFeedback(data.feedback || []);
      if (data.origin) setPublicOrigin(data.origin);
      return data;
    } catch (actionError) {
      setError(actionError.message || "Не удалось выполнить действие");
      return null;
    }
  }

  async function importDecisions(items) {
    if (!items.length) return;
    try {
      await fetch("/api/public-share", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ projectId, action: "import_decisions", decisions: items }) });
    } catch { /* decisions remain visible even if activity import is delayed */ }
  }

  async function importFeedback(items) {
    if (!items.length) return;
    try {
      await fetch("/api/public-share", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ projectId, action: "import_feedback", feedback: items }) });
    } catch { /* feedback remains visible even if activity import is delayed */ }
  }

  async function replyFeedback(item) {
    const message = String(feedbackDrafts[item.id] || "").trim();
    if (!message) return;
    setFeedbackBusy(item.id);
    const data = await action({ action: "feedback_reply", feedbackId: item.id, message });
    if (data) setFeedbackDrafts(previous => ({ ...previous, [item.id]: "" }));
    setFeedbackBusy("");
  }

  async function changeFeedbackStatus(item, nextStatus) {
    setFeedbackBusy(item.id);
    await action({ action: "feedback_status", feedbackId: item.id, status: nextStatus });
    setFeedbackBusy("");
  }

  async function createUpdate(event) {
    event.preventDefault();
    if (!updateDraft.title.trim() || !updateDraft.content.trim()) return;
    setUpdateBusy("create");
    const data = await action({ action: "create_update", title: updateDraft.title, content: updateDraft.content, category: updateDraft.category, pinned: updateDraft.pinned });
    if (data) setUpdateDraft({ title: "", content: "", category: "progress", pinned: false });
    setUpdateBusy("");
  }

  async function toggleUpdatePin(item) {
    setUpdateBusy(item.id);
    await action({ action: "pin_update", updateId: item.id, pinned: !item.pinned });
    setUpdateBusy("");
  }

  async function deleteUpdate(item) {
    if (confirmUpdateDelete !== item.id) { setConfirmUpdateDelete(item.id); return; }
    setConfirmUpdateDelete("");
    setUpdateBusy(item.id);
    await action({ action: "delete_update", updateId: item.id });
    setUpdateBusy("");
  }

  async function createShare(event) {
    event.preventDefault();
    const projectIds = selectedProjectIds.length ? selectedProjectIds : [projectId];
    const data = await action({ action: "create", days: Number(days), pin, projectIds });
    if (!data?.created) return;
    setCredentials({ url: `${data.origin}/share/${data.created.token}`, pin: data.created.pin, expiresAt: data.created.expiresAt, projectCount: projectIds.length });
    setPin("");
    const documents = documentsFor(data.snapshot, projectIds);
    if (documents.length) await syncDocuments(documents);
  }

  function toggleProject(nextProjectId) {
    if (nextProjectId === projectId) return;
    setSelectedProjectIds(current => current.includes(nextProjectId) ? current.filter(id => id !== nextProjectId) : [...current, nextProjectId].slice(0, 20));
  }

  async function syncDocuments(documents = publishedDocuments) {
    if (!documents.length) {
      setSyncStatus("done");
      setSyncMessage("Нет опубликованных документов для синхронизации");
      return;
    }
    setSyncStatus("syncing");
    setSyncMessage(`Подготавливаю документы: 0 из ${documents.length}`);
    let completed = 0;
    const failures = [];
    for (const document of documents) {
      try {
        const source = await fetch(`/api/files?id=${encodeURIComponent(document.id)}`, { cache: "no-store" });
        if (!source.ok) throw new Error("Не удалось прочитать внутренний файл");
        const buffer = await source.arrayBuffer();
        const digestBytes = await crypto.subtle.digest("SHA-256", buffer);
        const digest = Array.from(new Uint8Array(digestBytes), byte => byte.toString(16).padStart(2, "0")).join("");
        const signResponse = await fetch("/api/public-share", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ projectId, action: "prepare_file_upload", fileId: document.id, size: buffer.byteLength, digest }) });
        const signEnvelope = await signResponse.json();
        if (!signResponse.ok) throw new Error(signEnvelope.error || "Не удалось подготовить публикацию");
        const prepared = await relay(signEnvelope);
        const upload = await fetch(`${prepared.upload.endpoint}?token=${encodeURIComponent(prepared.upload.token)}`, { method: "PUT", headers: { "Content-Type": document.type || "application/octet-stream" }, body: buffer });
        const uploadResult = await upload.json();
        if (!upload.ok) throw new Error(uploadResult.error || "Не удалось опубликовать документ");
        completed += 1;
        setSyncMessage(`Подготавливаю документы: ${completed} из ${documents.length}`);
      } catch (syncError) {
        failures.push(document.name || document.id);
      }
    }
    if (failures.length) {
      setSyncStatus("error");
      setSyncMessage(`Опубликовано ${completed} из ${documents.length}. Не удалось: ${failures.join(", ")}`);
    } else {
      setSyncStatus("done");
      setSyncMessage(`Документы готовы к скачиванию: ${completed}`);
    }
  }

  async function rotatePin(item) {
    const data = await action({ action: "rotate_pin", shareId: item.id });
    if (data?.rotated) setCredentials({ url: `${data.origin}/share/${item.token}`, pin: data.rotated.pin, expiresAt: item.expiresAt });
  }

  async function revoke(item) {
    if (confirmRevoke !== item.id) { setConfirmRevoke(item.id); return; }
    setConfirmRevoke("");
    await action({ action: "revoke", shareId: item.id });
  }

  async function copy(value, key) {
    try {
      await navigator.clipboard.writeText(value);
      setCopied(key);
      setTimeout(() => setCopied(""), 1600);
    } catch { setError("Не удалось скопировать автоматически"); }
  }

  return (
    <section className="public-share-manager">
      <div className="public-share-head"><div><span className="section-kicker">Доступ без регистрации</span><h3>Публичные ссылки</h3><p>Ссылка открывает опубликованные этапы и документы, а также защищённый диалог с клиентом.</p></div><div className="public-share-head-actions"><button onClick={() => syncDocuments()} disabled={syncStatus === "syncing"} title="Подготовить документы для скачивания"><Download size={14} /> Файлы</button><button onClick={loadShares} title="Обновить"><RefreshCw size={15} className={status === "loading" ? "spin" : ""} /></button></div></div>

      <form className="public-share-create portfolio-create" onSubmit={createShare}><fieldset className="public-share-projects"><legend><Layers3 size={13} /> Проекты в этой ссылке <span>{selectedProjectIds.length}</span></legend><div>{projects.map(item => { const checked = selectedProjectIds.includes(item.id); const required = item.id === projectId; return <label key={item.id} className={checked ? "selected" : ""}><input type="checkbox" checked={checked} disabled={required} onChange={() => toggleProject(item.id)} /><i style={{ background: item.color || "#52725f" }} /><span>{item.name}</span>{required && <em>Основной</em>}</label>; })}</div></fieldset><label><span>Срок действия</span><select value={days} onChange={(event) => setDays(event.target.value)}><option value="3">3 дня</option><option value="7">7 дней</option><option value="14">14 дней</option><option value="30">30 дней</option><option value="90">90 дней</option></select></label><label><span>PIN-код</span><input inputMode="numeric" pattern="[0-9]{4,10}" value={pin} onChange={(event) => setPin(event.target.value.replace(/\D/g, "").slice(0, 10))} placeholder="Автоматически" /></label><button type="submit" disabled={status === "loading"}><Link2 size={15} /> Создать ссылку на {selectedProjectIds.length} {selectedProjectIds.length === 1 ? "проект" : selectedProjectIds.length < 5 ? "проекта" : "проектов"}</button></form>

      {error && <div className="public-share-error">{error}</div>}
      {syncMessage && <div className={`public-share-sync sync-${syncStatus}`}>{syncStatus === "syncing" && <LoaderCircle className="spin" size={13} />}<span>{syncMessage}</span></div>}
      {credentials && <div className="public-share-credentials"><span className="public-share-shield"><ShieldCheck size={20} /></span><div><strong>Ссылка готова · {credentials.projectCount || 1} {(credentials.projectCount || 1) === 1 ? "проект" : "проекта"}</strong><p>Передайте ссылку и PIN разными сообщениями. Сотрудники смогут переключать проекты внутри портала.</p><div><button onClick={() => copy(credentials.url, "url")}><span>{credentials.url}</span>{copied === "url" ? <Check size={14} /> : <Copy size={14} />}</button><button onClick={() => copy(credentials.pin, "pin")}><span>PIN: {credentials.pin}</span>{copied === "pin" ? <Check size={14} /> : <Copy size={14} />}</button></div><small>Действует до {formatDate(credentials.expiresAt)}</small></div></div>}

      <div className="public-updates-manager"><div className="public-updates-head"><div><span className="section-kicker">Публикации для клиента</span><h4>Лента обновлений</h4><p>Сообщайте о прогрессе, важных событиях, новых документах и изменениях сроков.</p></div><span><Newspaper size={14} /> {updates.length}</span></div><div className="public-updates-layout"><form className="public-updates-form" onSubmit={createUpdate}><div><label><span>Категория</span><select value={updateDraft.category} onChange={event => setUpdateDraft({ ...updateDraft, category: event.target.value })}><option value="progress">Прогресс</option><option value="milestone">Веха</option><option value="document">Документы</option><option value="deadline">Сроки</option><option value="important">Важно</option></select></label><label><span>Заголовок</span><input value={updateDraft.title} onChange={event => setUpdateDraft({ ...updateDraft, title: event.target.value.slice(0, 180) })} placeholder="Что изменилось" required minLength="3" /></label></div><label><span>Текст обновления</span><textarea rows="4" value={updateDraft.content} onChange={event => setUpdateDraft({ ...updateDraft, content: event.target.value.slice(0, 5000) })} placeholder="Коротко опишите результат, решение или следующий шаг" required minLength="3" /></label><div className="public-updates-submit"><label className="public-update-pin"><input type="checkbox" checked={updateDraft.pinned} onChange={event => setUpdateDraft({ ...updateDraft, pinned: event.target.checked })} /><i><Pin size={11} /></i><span>Закрепить запись</span></label><button type="submit" disabled={updateBusy === "create" || !updateDraft.title.trim() || !updateDraft.content.trim()}>{updateBusy === "create" ? "Публикую…" : "Опубликовать"}</button></div></form><div className="public-updates-list">{updates.length ? updates.map(item => <article key={item.id} className={`public-update-item update-${item.category}${item.pinned ? " pinned" : ""}`}><div className="public-update-marker">{item.pinned ? <Pin size={13} /> : <Newspaper size={13} />}</div><div><small>{updateCategory(item.category)} · {formatDate(item.publishedAt)}</small><strong>{item.title}</strong><p>{item.body}</p><em>{item.createdBy}</em></div><div className="public-update-actions"><button type="button" className={item.pinned ? "active" : ""} onClick={() => toggleUpdatePin(item)} disabled={updateBusy === item.id} title={item.pinned ? "Открепить" : "Закрепить"}><Pin size={12} /></button><button type="button" className={confirmUpdateDelete === item.id ? "confirm" : ""} onClick={() => deleteUpdate(item)} onBlur={() => setTimeout(() => setConfirmUpdateDelete(""), 150)} disabled={updateBusy === item.id} title="Удалить"><Trash2 size={12} />{confirmUpdateDelete === item.id && <span>Подтвердить</span>}</button></div></article>) : <div className="public-updates-empty"><Newspaper size={20} /><span>Публикаций пока нет</span></div>}</div></div></div>

      {feedback.length > 0 && <div className="public-feedback-inbox"><div className="public-feedback-head"><div><span className="section-kicker">Диалог с клиентом</span><h4>Обратная связь</h4></div><span>{feedback.filter(item => item.status === "new").length} новых</span></div><div className="public-feedback-list">{feedback.map(item => <article key={item.id} className={`public-feedback-card feedback-${item.status}`}><div className="public-feedback-title"><span><MessageSquare size={15} /></span><div><small>{item.category === "stage" ? `Этап${item.taskTitle ? ` · ${item.taskTitle}` : ""}` : item.category === "document" ? "Документы" : "Общий вопрос"}</small><strong>{item.subject}</strong><em>{item.clientName}{item.clientContact ? ` · ${item.clientContact}` : ""} · {formatDate(item.createdAt)}</em></div><b>{item.status === "resolved" ? "Решено" : item.status === "in_progress" ? "В работе" : "Новое"}</b></div><div className="public-feedback-messages">{(item.messages || []).map(message => <div key={message.id} className={`public-feedback-message message-${message.authorType}`}><div><strong>{message.authorName}</strong><time>{formatDate(message.createdAt)}</time></div><p>{message.body}</p></div>)}</div><div className="public-feedback-reply"><textarea rows="2" value={feedbackDrafts[item.id] || ""} onChange={event => setFeedbackDrafts(previous => ({ ...previous, [item.id]: event.target.value.slice(0, 3000) }))} placeholder="Ответить клиенту…" /><button onClick={() => replyFeedback(item)} disabled={feedbackBusy === item.id || !String(feedbackDrafts[item.id] || "").trim()}><Send size={13} /> Ответить</button></div><div className="public-feedback-status"><button className={item.status === "in_progress" ? "active" : ""} onClick={() => changeFeedbackStatus(item, "in_progress")} disabled={feedbackBusy === item.id}><Clock3 size={12} /> В работу</button><button className={item.status === "resolved" ? "active resolved" : ""} onClick={() => changeFeedbackStatus(item, "resolved")} disabled={feedbackBusy === item.id}><CircleCheck size={12} /> Решено</button>{item.status !== "new" && <button onClick={() => changeFeedbackStatus(item, "new")} disabled={feedbackBusy === item.id}>Вернуть в новые</button>}</div></article>)}</div></div>}

      {decisions.length > 0 && <div className="public-decision-list"><div className="public-decision-head"><div><span className="section-kicker">Согласование</span><h4>Решения клиента</h4></div><span>{decisions.length}</span></div>{decisions.map(item => <article key={item.id} className={`decision-${item.decision}`}><span>{item.decision === "approved" ? <Check size={15} /> : <RefreshCw size={15} />}</span><div><strong>{item.taskTitle}</strong><small>{item.decision === "approved" ? "Этап согласован" : "Запрошены изменения"} · {item.clientName} · {formatDate(item.decidedAt)}</small>{item.comment && <p>{item.comment}</p>}</div></article>)}</div>}

      <div className="public-share-list">{shares.map((item) => <article key={item.id} className={`share-${item.state}`}><span className="public-share-state">{item.state === "active" ? <ShieldCheck size={17} /> : <ShieldOff size={17} />}</span><div className="public-share-main"><div><strong>{item.state === "active" ? "Активная ссылка" : item.state === "expired" ? "Срок истёк" : "Ссылка отозвана"}</strong><span><Eye size={12} /> {item.viewCount || 0} просмотров</span></div>{item.projectNames?.length > 0 && <span className="public-share-project-summary"><Layers3 size={11} /> {item.projectNames.join(" · ")}</span>}<button onClick={() => copy(shareUrl(item.token), `link-${item.id}`)}><span>{shareUrl(item.token)}</span>{copied === `link-${item.id}` ? <Check size={13} /> : <Copy size={13} />}</button><small>Создана {formatDate(item.createdAt)} · до {formatDate(item.expiresAt)}{item.lastViewedAt ? ` · открывали ${formatDate(item.lastViewedAt)}` : ""}</small></div>{item.state === "active" && <div className="public-share-row-actions"><button onClick={() => rotatePin(item)} title="Сменить PIN"><KeyRound size={14} /></button><button className={confirmRevoke === item.id ? "confirm" : ""} onClick={() => revoke(item)} onBlur={() => setTimeout(() => setConfirmRevoke(""), 150)}>{confirmRevoke === item.id ? "Подтвердить" : "Отозвать"}</button></div>}</article>)}{status === "loading" && !shares.length ? <div className="public-share-empty"><LoaderCircle className="spin" size={20} /> Загружаю ссылки…</div> : status !== "loading" && !shares.length && <div className="public-share-empty"><Link2 size={20} /> Активных ссылок пока нет</div>}</div>
    </section>
  );
}
